# Generated by Django 5.0.7 on 2024-11-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_desc', models.TextField()),
                ('slider_head', models.CharField(max_length=100)),
                ('slider_btn', models.CharField(max_length=50)),
                ('slider_image', models.ImageField(upload_to='slides/')),
            ],
        ),
    ]
