# Generated by Django 5.0.7 on 2024-11-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_desc', models.TextField()),
                ('feature_title', models.CharField(max_length=100)),
                ('icon_class', models.CharField(max_length=100)),
            ],
        ),
    ]
