# Generated by Django 5.0.7 on 2024-11-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_title', models.CharField(max_length=255)),
                ('info_description', models.TextField()),
                ('info_image', models.ImageField(blank=True, null=True, upload_to='info/')),
                ('info_feature_1', models.TextField()),
                ('info_feature_2', models.TextField()),
                ('info_feature_3', models.TextField()),
                ('info_desc_2', models.TextField()),
            ],
        ),
    ]
