# Generated by Django 5.0.7 on 2024-11-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0006_rename_about_desc_sections_sect_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
    ]
