# Generated by Django 5.0.7 on 2024-11-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0007_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_desc', models.TextField()),
                ('part_title', models.CharField(max_length=100)),
                ('part_icon', models.CharField(max_length=100)),
            ],
        ),
    ]
