# Generated by Django 5.0.7 on 2024-11-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0008_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_desc', models.TextField()),
                ('action_head', models.CharField(max_length=100)),
                ('action_btn', models.CharField(max_length=50)),
            ],
        ),
    ]
