# Generated by Django 5.0.7 on 2024-11-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0009_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_head', models.CharField(max_length=255)),
                ('title_desc', models.TextField()),
            ],
        ),
    ]
