# Generated by Django 5.0.7 on 2024-11-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0010_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('category', models.CharField(choices=[('app', 'App'), ('product', 'Product'), ('branding', 'Branding'), ('books', 'Books')], max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
