# Generated by Django 5.0.7 on 2024-11-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0011_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='url',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('app', 'Business Insights'), ('product', 'Machine Learning Models'), ('branding', 'Visualization Projects'), ('books', 'Forecasting & Predictions')], max_length=50),
        ),
    ]
