# Generated by Django 5.0.7 on 2024-11-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0012_remove_portfolio_url_alter_portfolio_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_head', models.CharField(max_length=255)),
                ('team_desc', models.TextField()),
            ],
        ),
    ]
